name: Build and test SQRL with Maven
on:
 workflow_dispatch:
    inputs:
      repo:
        description: Test runner
        required: true
        default: 'zharec'
        type: string
      note:
        description: Test note
        required: true
        default: 'Smoke test'
        type: string
      example:
        description: Example to test
        required: true
        type: choice
        default: healthcare
        options:
          - finance
          - healthcare
          - logistics
          - iot-sensor
          - retail
 pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: 'America/Los_Angeles'
    steps:
    - name: Setup Timezone
      uses: szenius/set-timezone@v1.1
      with:
        timezoneLinux: "America/Los_Angeles"

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Debugging login
      run: |
        echo "Logging in with user: ${{ secrets.DOCKER_USERNAME }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull SQRL demo Docker image
      run: docker pull datasqrl/sqrl-demo:latest

    - name: Run Healthcare Analytics Test
      if: ${{ github.event.inputs.example == 'healthcare' }}
      working-directory: ./healthcare-study-monitoring
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build -e LOCAL_WAREHOUSE_DIR=/tmp/warehouse datasqrl/sqrl-demo:latest test -c study_analytics_package.json study_analytics.sqrl --snapshot snapshots-study-analytics
      continue-on-error: false

    - name: Run Healthcare Study Api Test
      if: ${{ github.event.inputs.example == 'healthcare' }}
      working-directory: ./healthcare-study-monitoring
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build datasqrl/sqrl-demo:latest test -c study_api_test_package.json --tests tests-api --snapshot snapshots-study-api
      continue-on-error: false

    - name: Run Healthcare Study Stream Test
      if: ${{ github.event.inputs.example == 'healthcare' }}
      working-directory: ./healthcare-study-monitoring
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build datasqrl/sqrl-demo:latest test -c study_stream_local_package.json study_stream.sqrl --snapshot snapshots-study-stream
      continue-on-error: false

    - name: Run Healthcare Create Api Test
      if: ${{ github.event.inputs.example == 'healthcare' }}
      working-directory: ./healthcare-study-monitoring
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build datasqrl/sqrl-demo:latest compile study_create_api.sqrl
      continue-on-error: false

    - name: Run Finance Analytics Test
      if: ${{ github.event.inputs.example == 'finance' }}
      working-directory: ./finance-credit-card-chatbot
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build datasqrl/sqrl-demo:latest test -c package-analytics-local.json --snapshot snapshots-analytics
      continue-on-error: false

    - name: Run Finance Rewards Test
      if: ${{ github.event.inputs.example == 'finance' }}
      working-directory: ./finance-credit-card-chatbot
      run: |
        docker run -i -p 8888:8888 -p 8081:8081 --rm -v $PWD:/build datasqrl/sqrl-demo:latest test test -c package-rewards-local.json --snapshot snapshots-rewards
      continue-on-error: false
    
    - name: Run anyway
      if: ${{ github.event.inputs.example != 'healthcare' }}
      run: |
        echo "This ran, I guess that is a good thing"
      continue-on-error: true

