name: deploy

on:
  pull_request:
    branches:
      - "main"

concurrency:
  # If you have multiple workflows in the same repository,
  # concurrency group names must be unique across workflows to avoid canceling in-progress jobs or runs from other workflows.
  # Otherwise, any previously in-progress or pending job will be canceled, regardless of the workflow.
  # To only cancel in-progress runs of the same workflow, you can use the github.workflow property to build the concurrency group:

  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EXAMPLE_NAME: finance-credit-card-chatbot
  DEPLOYMENT_PACKAGE_NAME: package-analytics-no-chat


jobs:
  build-artifacts:
    name: "BuildArtifacts"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    env:
      ENV: DEV
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Getting Code
        uses: actions/checkout@v3

      - name: Build Artifacts
        run: |
          cd "${{ github.workspace }}/$EXAMPLE_NAME"
          docker run --rm -v $PWD:/build datasqrl/cmd:v0.5.2 compile -c "$DEPLOYMENT_PACKAGE_NAME.json"
          cd build/deploy
          ls -la
          docker compose build
          docker images
        shell: bash
      
      - name: Create ECR repo if necessary
        id: ecr-repo
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: "datasqrl-examples/finance-credit-card-chatbot/package-analytics-no-chat/deploy-server"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Tag and Push Docker Images to ECR repository, Upload artifacts to S3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          export ECR_REPOSITORY="datasqrl-examples/${EXAMPLE_NAME}/${DEPLOYMENT_PACKAGE_NAME}"
          export IMAGE_TAG="$ECR_REGISTRY/$ECR_REPOSITORY/deploy-server:latest"
          docker tag deploy-server:latest $IMAGE_TAG
          docker push $IMAGE_TAG

          # upload jar file
          docker create --name temp_container deploy-flink-job-submitter
          sudo docker cp temp_container:/scripts/FlinkJob.jar .
          docker rm temp_container
          aws s3 cp FlinkJob.jar s3://sqrl-examples-artifactory-dev/datasqrl-examples/${EXAMPLE_NAME}/${DEPLOYMENT_PACKAGE_NAME}/

          # upload database schema
          cd ${{ github.workspace }}/finance-credit-card-chatbot/build/deploy/postgres/
          aws s3 cp database-schema.sql s3://sqrl-examples-artifactory-dev/datasqrl-examples/${EXAMPLE_NAME}/${DEPLOYMENT_PACKAGE_NAME}/
        shell: bash
      
      - name: Deploy
        run: |
          cp /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/build/deploy/postgres/database-schema.sql  /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/mock_tf_build_deploy
          cp /home/runner/work/datasqrl-examples/datasqrl-examples/FlinkJob.jar /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/mock_tf_build_deploy
          cp -r /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/creditcard-local /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/mock_tf_build_deploy

          ls -la /home/runner/work/datasqrl-examples/datasqrl-examples/finance-credit-card-chatbot/mock_tf_build_deploy
        shell: bash
      
      - name: Set up SSH to sqrl-cloud repo
        id: ssh_setup
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          docker pull public.ecr.aws/j5u7a3j2/datasqrl/cloud:latest
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_SQRL_CLOUD }}

      - name: Terraform Plan
        id: plan
        run: |
            cd finance-credit-card-chatbot/mock_tf_build_deploy
            docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_REGION -v ~/.ssh:/root/.ssh -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock public.ecr.aws/j5u7a3j2/datasqrl/cloud:latest terraform init -backend-config='bucket=sqrl-examples-artifactory-dev' -backend-config='key=datasqrl-examples/finance-credit-card-chatbot/package-analytics-no-chat' -backend-config='region=us-east-1'
            docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_REGION -v ~/.ssh:/root/.ssh -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock public.ecr.aws/j5u7a3j2/datasqrl/cloud:latest terraform plan
        shell: bash
      
      - name: Terraform Apply
        id: apply
        run: |
            cd finance-credit-card-chatbot/mock_tf_build_deploy
            docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_REGION -v ~/.ssh:/root/.ssh -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock public.ecr.aws/j5u7a3j2/datasqrl/cloud:latest terraform init -backend-config='bucket=sqrl-examples-artifactory-dev' -backend-config='key=datasqrl-examples/finance-credit-card-chatbot/package-analytics-no-chat' -backend-config='region=us-east-1'
            docker run --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_REGION -v ~/.ssh:/root/.ssh -v "$(pwd)":/app -v /var/run/docker.sock:/var/run/docker.sock public.ecr.aws/j5u7a3j2/datasqrl/cloud:latest terraform apply --auto-approve
        shell: bash
  
  # deploy test infrastructure