name: CI

on:
  pull_request:
    branches:
      - "main"

concurrency:
  # If you have multiple workflows in the same repository,
  # concurrency group names must be unique across workflows to avoid canceling in-progress jobs or runs from other workflows.
  # Otherwise, any previously in-progress or pending job will be canceled, regardless of the workflow.
  # To only cancel in-progress runs of the same workflow, you can use the github.workflow property to build the concurrency group:

  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EXAMPLE_NAME: finance-credit-card-chatbot
  DEPLOYMENT_PACKAGE_NAME: package-analytics-local.json


jobs:
  build-artifacts:
    name: "BuildArtifacts"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    env:
      ENV: DEV
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          # TODO: change value of secrets AWS_DEV_GITHUB_ACTION_ROLE to arn instead of name now 
          # role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          role-to-assume: arn:aws:iam::286928876767:role/${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Getting Code
        uses: actions/checkout@v3

      - name: Build Artifacts
        run: |
          cd ${{ github.workspace }}/finance-credit-card-chatbot
          docker run --rm -v $PWD:/build datasqrl/cmd:v0.5.2 compile -c {{ env.DEPLOYMENT_PACKAGE_NAME }}
          cd build/deploy
          ls -la
          docker compose build
          docker images
        shell: bash
      
      - name: Create ECR repo if necessary
        id: ecr-repo
        uses: int128/create-ecr-repository-action@v1
        with:
          repository: "datasqrl-examples/finance-credit-card-chatbot/package-analytics-local/deploy-server"
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Tag and Push Docker Images to ECR repository, Upload artifacts to S3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # IMAGE_TAG: ${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}
        run: |
          export ECR_REPOSITORY="datasqrl-examples/finance-credit-card-chatbot/package-analytics-kafka"
          export IMAGE_TAG="$ECR_REGISTRY/$ECR_REPOSITORY/deploy-server:latest"
          docker tag deploy-server:latest $IMAGE_TAG
          docker push $IMAGE_TAG

          # upload jar file
          docker create --name temp_container deploy-flink-job-submitter
          sudo docker cp temp_container:/scripts/FlinkJob.jar .
          docker rm temp_container
          aws s3 cp FlinkJob.jar s3://sqrl-examples-artifactory-dev/datasqrl-examples/finance-credit-card-chatbot/package-analytics-kafka/

          # upload database schema
          cd ${{ github.workspace }}/finance-credit-card-chatbot/build/deploy/postgres/database-schema.sql
          aws s3 cp database-schema.sql s3://sqrl-examples-artifactory-dev/datasqrl-examples/finance-credit-card-chatbot/package-analytics-kafka/
        shell: bash
      
      - name: Deploy
        run: |
          echo "deploy cloud resources"
        shell: bash
  
  # deploy test infrastructure